// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvPhh7jvzRAKBQ5gAGYKx0R2Y-UPT6Oo',
    appId: '1:83868112810:web:70b0ae1dc908752100fdd3',
    messagingSenderId: '83868112810',
    projectId: 'sikatronicequipment',
    authDomain: 'sikatronicequipment.firebaseapp.com',
    storageBucket: 'sikatronicequipment.appspot.com',
    measurementId: 'G-G55WTYC14F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_VX9sf9VZ6OytjwUDVO1YIWBAFwoy6eQ',
    appId: '1:83868112810:android:0fd98ba90d0753be00fdd3',
    messagingSenderId: '83868112810',
    projectId: 'sikatronicequipment',
    storageBucket: 'sikatronicequipment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClwKzh9ygzHtJhB76GDnsUV8ZBHe8Ndk',
    appId: '1:83868112810:ios:58f728c13734adad00fdd3',
    messagingSenderId: '83868112810',
    projectId: 'sikatronicequipment',
    storageBucket: 'sikatronicequipment.appspot.com',
    iosClientId:
        '83868112810-jaoctaj407lbpkhlji0lgaupleddtbep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikatronicsEquipment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBClwKzh9ygzHtJhB76GDnsUV8ZBHe8Ndk',
    appId: '1:83868112810:ios:58f728c13734adad00fdd3',
    messagingSenderId: '83868112810',
    projectId: 'sikatronicequipment',
    storageBucket: 'sikatronicequipment.appspot.com',
    iosClientId:
        '83868112810-jaoctaj407lbpkhlji0lgaupleddtbep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikatronicsEquipment',
  );
}
